### ISSUE TITLE
Aggiungere Dataset Sicurezza

### ISSUE THREAD

**Issue by ipersoft** [comune-desio/map#1]
- [ ] Punti DAE
- [ ] Ospedale
- [ ] Punti di raccolta (protezione civile)

@olistik @favoeva

**Comment by olistik** [comment]
@ipersoft sono tutti dataset che abbiamo già a disposizione o ne manca qualcuno?

**Comment by ipersoft** [comment]
@olistik ospedale è uno, i punti di raccolta bisogna chiede a @favoeva

**Comment by olistik** [comment]
Aggiunta la issue sul repository opendata: https://github.com/comune-desio/opendata/issues/27

**Comment by olistik** [comment]
chiudo questa issue dato che le necessità di creazione di mappe si sposteranno, almeno nell'immediato, dentro dati.lombardia.it
