### ISSUE TITLE
Supporto HTTPS?

### ISSUE THREAD

**Issue by olistik** [comune-desio/map#2]
@ipersoft serve che la pagina sia ospitata sotto HTTPS?

Le opzioni:
1. passare da Netlify mantenendo il nostro dominio custom map.desio.org
2. lasciare l'hosting su GitHub Pages ma avere map.desio.org solo come redirect verso comune-desio.github.io/map

Io propenderei per la 1.

**Comment by ipersoft** [comment]
@olistik 
Con il punto 1 basta modificare il reposity che viene aggiornata in automatico?

**Comment by olistik** [comment]
@ipersoft esatto.

**Comment by ipersoft** [comment]
Per me puoi procedere

**Comment by olistik** [comment]
1. Commit: https://github.com/comune-desio/map/commit/0fc1d66511372f2b437e1f55913c12bca925ea52
2. Configurazione di DatoCMS
3. Configurazione di Netlify

La mappa è ora semi-dinamicizzata e servita con HTTPS ;-)
